name: Generate
on:
  schedule:
    - cron:  '* 10 * * *'

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@1.4.4
      with:
        php-version: 7.3
        extension-csv: xmlwriter # @TODO might not be needed

    - name: Debugging
      run: |
        php --version
        php -m
        composer --version

    - name: Install dependencies
      run: composer install --prefer-dist --no-suggest

    - name: Generate hooks
      run: composer generate

    - name: Run validation
      run: composer validate-files

      # @TODO bump version number (npm --no-git-tag-version version patch)
      # @TODO commit changes
      # @TODO tag in git using jq to get the new version number from package.json
      # @TODO push to github master
      # @TODO push tags to github
